spring:
  datasource:
    url: jdbc:mariadb://host.com:port/table?useUnicode=yes&characterEncoding=UTF-8
    username: username
    password: 'password'
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

server:
  port: 2021

